version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
# volumes:
# - /Users/jv/jv/mongo:/data/db
    ports:
      - 27017:27017
